/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as NuevoRouteImport } from './routes/nuevo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriaCategoryIdRouteImport } from './routes/categoria.$categoryId'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevoRoute = NuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaCategoryIdRoute = CategoriaCategoryIdRouteImport.update({
  id: '/categoria/$categoryId',
  path: '/categoria/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cuenta': typeof CuentaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/nuevo': typeof NuevoRoute
  '/ofertas': typeof OfertasRoute
  '/registro': typeof RegistroRoute
  '/tienda': typeof TiendaRoute
  '/categoria/$categoryId': typeof CategoriaCategoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cuenta': typeof CuentaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/nuevo': typeof NuevoRoute
  '/ofertas': typeof OfertasRoute
  '/registro': typeof RegistroRoute
  '/tienda': typeof TiendaRoute
  '/categoria/$categoryId': typeof CategoriaCategoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cuenta': typeof CuentaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/nuevo': typeof NuevoRoute
  '/ofertas': typeof OfertasRoute
  '/registro': typeof RegistroRoute
  '/tienda': typeof TiendaRoute
  '/categoria/$categoryId': typeof CategoriaCategoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cuenta'
    | '/faq'
    | '/login'
    | '/nuevo'
    | '/ofertas'
    | '/registro'
    | '/tienda'
    | '/categoria/$categoryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cuenta'
    | '/faq'
    | '/login'
    | '/nuevo'
    | '/ofertas'
    | '/registro'
    | '/tienda'
    | '/categoria/$categoryId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cuenta'
    | '/faq'
    | '/login'
    | '/nuevo'
    | '/ofertas'
    | '/registro'
    | '/tienda'
    | '/categoria/$categoryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CuentaRoute: typeof CuentaRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  NuevoRoute: typeof NuevoRoute
  OfertasRoute: typeof OfertasRoute
  RegistroRoute: typeof RegistroRoute
  TiendaRoute: typeof TiendaRoute
  CategoriaCategoryIdRoute: typeof CategoriaCategoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuevo': {
      id: '/nuevo'
      path: '/nuevo'
      fullPath: '/nuevo'
      preLoaderRoute: typeof NuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$categoryId': {
      id: '/categoria/$categoryId'
      path: '/categoria/$categoryId'
      fullPath: '/categoria/$categoryId'
      preLoaderRoute: typeof CategoriaCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CuentaRoute: CuentaRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  NuevoRoute: NuevoRoute,
  OfertasRoute: OfertasRoute,
  RegistroRoute: RegistroRoute,
  TiendaRoute: TiendaRoute,
  CategoriaCategoryIdRoute: CategoriaCategoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
